Repository AY2021S1-CS2113T-W13-2/tp, pull requests merged in 2020-10, with the labels that each got.

#54 Organise project into packages
  build.gradle
  src/main/java/fitr/Calorie.java
  src/main/java/fitr/Exercise.java
  src/main/java/fitr/Fitr.java
  src/main/java/fitr/Food.java
  src/main/java/fitr/command/AddExerciseCommand.java
  src/main/java/fitr/command/AddFoodCommand.java
  src/main/java/fitr/command/Command.java
  src/main/java/fitr/command/DeleteCommand.java
  src/main/java/fitr/command/ExitCommand.java
  src/main/java/fitr/command/HelpCommand.java
  src/main/java/fitr/command/InvalidCommand.java
  src/main/java/fitr/command/ViewCommand.java
  src/main/java/fitr/common/Commands.java
  src/main/java/fitr/common/Messages.java
  src/main/java/fitr/exception/FitrException.java
  src/main/java/fitr/list/ExerciseList.java
  src/main/java/fitr/list/FoodList.java
  src/main/java/fitr/parser/Parser.java
  src/main/java/fitr/storage/Storage.java
  src/main/java/fitr/ui/Ui.java
  src/main/java/fitr/user/User.java
  src/test/java/fitr/list/ExerciseListTest.java
  src/test/java/fitr/list/FoodListTest.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High, type.Task

#111 Fix crash when edit command is called without arguments
  src/main/java/fitr/parser/EditCommandParser.java
Labels: type.Bug

#113 Use one-step process for edit command
  docs/UserGuide.md
  src/main/java/fitr/Food.java
  src/main/java/fitr/command/EditEntryCommand.java
  src/main/java/fitr/common/Messages.java
  src/main/java/fitr/parser/EditCommandParser.java
  src/main/java/fitr/ui/Ui.java
Labels: type.Task

#114 Refactor lists
  src/main/java/fitr/Fitr.java
  src/main/java/fitr/Recommender.java
  src/main/java/fitr/command/AddExerciseCommand.java
  src/main/java/fitr/command/AddFoodCommand.java
  src/main/java/fitr/command/AddGoalCommand.java
  src/main/java/fitr/command/ClearCommand.java
  src/main/java/fitr/command/Command.java
  src/main/java/fitr/command/DeleteCommand.java
  src/main/java/fitr/command/EditEntryCommand.java
  src/main/java/fitr/command/EditProfileCommand.java
  src/main/java/fitr/command/ExitCommand.java
  src/main/java/fitr/command/HelpCommand.java
  src/main/java/fitr/command/InvalidCommand.java
  src/main/java/fitr/command/RecommendCommand.java
  src/main/java/fitr/command/ViewCommand.java
  src/main/java/fitr/list/ListManager.java
  src/main/java/fitr/list/StandardExerciseList.java
  src/main/java/fitr/storage/StandardExerciseStorage.java
  src/main/java/fitr/storage/StorageManager.java
Labels: type.Task

#117 Improve caloric summary view
  docs/UserGuide.md
  src/main/java/fitr/command/ViewCommand.java
Labels: priority.High
